
name: Build documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Setup uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies (uv)
        run: |
          uv sync --group docs

      - name: Build documentation
        run: |
          cd docs
          uv run mkdocs gh-deploy --remote-branch gh-pages
