# GitHub Action: Generate docs and check for changes
name: Check documentation freshness

on: [pull_request]

jobs:
  check-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pdoc

      - name: Generate documentation
        run: |
          pdoc -o docs src/diffhouse

      - name: Check for changes
        run: |
          if [ "$(git status --porcelain docs/*.html)" != "" ]; then
            echo "Documentation files are out of date."
            exit 1
          fi
