name: Test package

on: [pull_request, workflow_dispatch]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # for GitHub API requests

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3"]
        git_version: ["2.22.0", "latest"]
        include:
          # Git has different version schemes on Windows; adding mapping here
          - os: windows-latest
            git_version: "2.22.0"
            windows_git_version: "2.22.0.windows.1"
      fail-fast: false
    
    steps:
      # Install a specific Git version when not using 'latest'
      - name: Setup Git (Linux/macOS)
        if: matrix.git_version != 'latest' && runner.os != 'Windows'
        uses: isikerhan/setup-git@v1
        with:
          git-version: ${{ matrix.git_version }}

      # Same for Windows, using the Windows-specific version
      - name: Setup Git (Windows)
        if: matrix.git_version != 'latest' && runner.os == 'Windows'
        uses: isikerhan/setup-git@v1
        with:
          git-version: ${{ matrix.windows_git_version }}

      - name: Set up uv
        uses: astral-sh/setup-uv@v6

      - name: Checkout repository
        uses: actions/checkout@v5
      
      # This installs Python as well
      - name: Install dependencies (uv)
        run: |
          uv sync --python ${{ matrix.python-version }}

      - name: Run tests
        run: uv run pytest -v
